version: 2

sources:
  - name: scr_nowflake_sample_data
    description: 'A sample database provided by Snowflake.'
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCDS_SF10TCL 
    tables:
      - name: STORE_SALES
        description: 'Details about the sales in the store'

  